添加微软的合成发音, 不需要跳转页面, 代码修改小, 再安装 pywin32
Zeroto521/Wox.Plugin.Youdao pull request #5
Opened 2021-04-20 16:12 UTC by TanCheamy

不好意, 第一次使用 Pull Requests, 如果有问题, 请多多包涵

2021-04-21 13:03 UTC, Zeroto521 commented on youdao/youdao.py
> +        if translation:
我认为 **发音** 与 **复制** 是两个动作, 因此最好分开.

当然, 你也可以三个都有, **发音**, **复制**, **复制并发音**

2021-04-21 13:12 UTC, Zeroto521 commented on requirements.txt
> +pyperclip==1.8.2
虽然加版本号好, 但考虑到未来兼容型, 这里还是不加为好.

因为该项目并非长期维护, 但依赖和解释器却是长期维护的. 所以还是让 `pip` 自行选择吧.

2021-04-21 13:16 UTC, Zeroto521 commented on youdao/youdao.py
> +from win32com.client import Dispatch
请使用 `isort` 来 **sort imports**

2021-04-21 13:35 UTC, TanCheamy commented
首先, 你觉得这个功能是否有添加的必要性, (微软 tts 支持 win7 以上系统)
如果有必要性是否由我重新修改提交合并

2021-04-21 13:46 UTC, Zeroto521 commented
> 首先, 你觉得这个功能是否有添加的必要性, (微软 tts 支持 win7 以上系统)

使用本地服务相较于网络服务肯定体验要更好些.

Wox 本身也不支持 win7 以下版本, https://github.com/Wox-launcher/Wox/issues/175

2021-04-21 13:54 UTC, TanCheamy commented on youdao/youdao.py
> +        if translation:
从功能性的角度出发, 是分开比较好, 比如: **发音, 复制, 复制并发音**
从我个人的使用习惯,  还是复制并发音用起来比较爽, (有时候只要发音或者复制, 与其作选择,  不如都要(有时候作选择也浪费时间))

2021-04-21 13:56 UTC, TanCheamy commented on requirements.txt
> +pyperclip==1.8.2
这个我没有什么意见

2021-04-21 14:05 UTC, TanCheamy commented on youdao/youdao.py
> +from win32com.client import Dispatch
抱歉, 我入门python不久(学过基础篇), 你的意思这样吗?
``` python
>> from isort import SortImports
>> SortImports("youdao.py")
```

2021-04-21 14:08 UTC, Zeroto521 commented on youdao/youdao.py
> +from win32com.client import Dispatch
https://pypi.org/project/isort/

或是 IDE 类似插件

2021-04-21 14:32 UTC, TanCheamy commented on youdao/youdao.py
> +        if translation:
这样如何?

![image](https://user-images.githubusercontent.com/77718171/115571202-5e6dbc00-a2f1-11eb-9adc-f770a06c6233.png)

2021-04-23 00:49 UTC, Zeroto521 commented on youdao/youdao.py
> +        if translation:
> anyway, just show me codes.

2021-04-23 09:17 UTC, TanCheamy commented on youdao/youdao.py
> +        if translation:
``` python
import pyperclip
from win32com.client import Dispatch

from wox import Wox

from .constants import *
```

``` python
        if translation:
            tit = translation[0]
            subtit = '点击复制到剪贴板并收藏'
            method = 'copy2clipboard'
            parameters = [q, translation[0]]
            res = self.genaction(tit, subtit, method, parameters)
            result.append(res)

        if translation:
            tit = q
            subtit = '点击发音'
            method = 'speak'
            parameters = [q]
            result.append(self.genaction(tit, subtit, method, parameters))
```

``` python
    def copy2clipboard(self, query, translation):
        """复制到剪切板

        Arguments:
            value -- 复制内容
        """
        self.record(query, translation)  # 记录
        pyperclip.copy(str(translation).strip())

    def speak(self, source):
        """发音

        :param query: source
        :return:
        """
        spVoice = Dispatch("SAPI.SpVoice")
        spVoice.Speak(source)
```

2021-04-23 12:20 UTC, Zeroto521 commented on youdao/youdao.py
> +        if translation:
了解下 pr 和 code review。

当在已提交pr的branch下提交commit皆会在该pr下呈现，这是所谓的 show me the codes。

2021-04-24 01:38 UTC, Zeroto521 requested changes

2021-04-24 01:38 UTC, Zeroto521 commented on youdao/youdao.py
> +        # tSpeakUrl = response.get('tSpeakUrl', '')
删除无用代码

2021-04-24 05:32 UTC, Zeroto521 approved these changes

2021-04-24 05:33 UTC, merged